### ISSUE TITLE
2 twist crate

### ISSUE THREAD

**Issue by brunoqc** [rustyhorde/twist#7]
Why is there 2 crates? It may be confusing.

- https://crates.io/crates/twist
- https://crates.io/crates/twists

If one was published in error, maybe you should yank it.

**Comment by CraZySacX** [comment]
twist is the library for implementing a server.  twists is an example echo server.   I'll update the docs to make that more clear.

**Comment by brunoqc** [comment]
Be sure to also make it clear on crates.io. I think you should have 2 Cargo.toml: one for the lib and one for the example echo server.

**Comment by CraZySacX** [comment]
Yeah certainly.  I'll make sure it's showing on crates.io that way.  There is already a separate Cargo.toml for twists at https://github.com/rustyhorde/twists.

**Comment by CraZySacX** [comment]
One other note, make sure you look at the latest Cargo.toml.   I pulled out the binaries into separate projects.
