### ISSUE TITLE
How to use as a stream-oriented protocol?

### ISSUE THREAD

**Issue by 4lbert** [rustyhorde/twist#8]
Hi,

I'm looking for a way to use this library without using services and structuring my server after a request/response structure. Basically, reading and writing to the connection is done independently of each other.

Looking at the tokio tutorial (https://tokio.rs/docs/going-deeper/transports/#using) the way to do this is to work directly with the codec/transport. However, I can't find a Codec in the library. Am I just missing it or is there another way?

Really grateful that you're creating this library. Thanks!

**Comment by CraZySacX** [comment]
The codec is [here](https://github.com/rustyhorde/twist/blob/master/src/codec/mod.rs).   However, it isn't currently exposed as part of the API.   It's sounds like you may have a need to just use the codec, so I could expose it.

**Comment by CraZySacX** [comment]
As a side note, you may want to wait until after my next few commits.  Autobahn testing has exposed some issues in the Codec that I'm currently resolving.

**Comment by 4lbert** [comment]
It would be nice to have access to the codec, thanks! Good luck with the Autobahn tests!

**Comment by CraZySacX** [comment]
The Codec implementations have been exposed as part of the API now.   BaseFrameCodec is likely what you are looking for.
